name       : snapd-glib
version    : '1.29'
release    : 4
source     :
    - https://github.com/snapcore/snapd-glib/releases/download/1.29/snapd-glib-1.29.tar.xz : 8e021b2c822f9d4e32ea9fa20a1f66605e6b84992a02336d7dbe41e959a60792
license    :
    - LGPL-3.0
component  : programming.library
summary    : glib library for communicating with snapd
description: |
    glib library for communicating with snapd
builddeps  :
    - pkgconfig(libsoup-2.4)
    - pkgconfig(json-glib-1.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/dbus-1/* $installdir/usr/share/.
    rmdir $installdir/etc/dbus-1
    rmdir $installdir/etc
