name       : snapd-glib
version    : '1.43'
release    : 7
source     :
    - https://github.com/snapcore/snapd-glib/releases/download/1.43/snapd-glib-1.43.tar.xz : 6e6d0ef19ce52d8a56c5fbf8c35004d3882cb5f2c4643f1b6944a3bc17519d43
license    : LGPL-3.0-or-later
component  : programming.library
summary    : glib library for communicating with snapd
description: |
    glib library for communicating with snapd
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
