name       : snapd-glib
version    : 1.23
release    : 2
source     :
    - https://github.com/snapcore/snapd-glib/releases/download/1.23/snapd-glib-1.23.tar.xz : bf1905279dbb0bc34057de304b50961d9ac41661e51b83d420d4e74e6e731907
license    :
    - LGPL-3.0
component  : programming.library
summary    : glib library for communicating with snapd
description: |
    glib library for communicating with snapd
builddeps  :
    - pkgconfig(libsoup-2.4)
    - pkgconfig(json-glib-1.0)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-runtime-assertion-when-snapd-socket-is-NULL.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/dbus-1/* $installdir/usr/share/.
    rmdir $installdir/etc/dbus-1
    rmdir $installdir/etc
    rm $installdir/%libdir%/pkgconfig/*qt.pc -v
