name       : snapd-glib
version    : '1.59'
release    : 16
source     :
    - https://github.com/snapcore/snapd-glib/releases/download/1.59/snapd-glib-1.59.tar.xz : 01e6424f4dfd46b736956c9dc4ef1932052590123b80f5b5a363dc9f51ae4690
license    : LGPL-3.0-or-later
component  : programming.library
summary    : glib library for communicating with snapd
description: |
    glib library for communicating with snapd
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
setup      : |
    %meson_configure -Ddocs=false \
                    -Dqt-bindings=false \
                    -Dqml-bindings=false \
                    -Dvala-bindings=false
build      : |
    %ninja_build
install    : |
    %ninja_install
