name       : snapd-glib
version    : '1.47'
release    : 9
source     :
    - https://github.com/snapcore/snapd-glib/releases/download/1.47/snapd-glib-1.47.tar.xz : 9c77791f08f86479987cc04e57a8db5f6aede6f81a644453227c2e8d147980a0
license    : LGPL-3.0-or-later
component  : programming.library
summary    : glib library for communicating with snapd
description: |
    glib library for communicating with snapd
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
