name       : snapd-glib
version    : '1.45'
release    : 8
source     :
    - https://github.com/snapcore/snapd-glib/releases/download/1.45/snapd-glib-1.45.tar.xz : aa204e17490f422375e6eb6a9d3d07f232931b89355a17cf70c4e42f8c155bb6
license    : LGPL-3.0-or-later
component  : programming.library
summary    : glib library for communicating with snapd
description: |
    glib library for communicating with snapd
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
