name       : snapd-glib
version    : '1.39'
release    : 6
source     :
    - https://github.com/snapcore/snapd-glib/releases/download/1.39/snapd-glib-1.39.tar.xz : 2b41e64fe1a6104a4e8bcf537dca12c43b14efa6a6ce85dfc6d4316e028328b8
license    : LGPL-3.0-or-later
component  : programming.library
summary    : glib library for communicating with snapd
description: |
    glib library for communicating with snapd
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
